# Generated by Django 4.1.7 on 2023-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_vietnamese',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
